import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "mapbox-gl/dist/mapbox-gl.css";
import "./globals.css";
import RootClient from "@/app/rootClient";
import { ThemeProvider } from "@/app/_components/providers/themeProvider";
import StateInitializer from "@/app/_components/layout/templates/stateInitializer";

//uxo

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//基本レイアウトファイル。サーバーコンポーネントとして実装する。

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} font-sans`}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
        <RootClient>{children}</RootClient>
          <StateInitializer/>
      </ThemeProvider>
      </body>
    </html>
  );
}
